# Generated by Django 2.2.1 on 2019-09-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('skilled_workforce_count', models.IntegerField()),
                ('unskilled_workforce_count', models.IntegerField()),
                ('skilled_workforce_sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unskilled_workforce_sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skilled_workforce_age', models.IntegerField()),
                ('unskilled_workforce_age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], max_length=1)),
            ],
        ),
    ]
