# Generated by Django 2.2.1 on 2019-10-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], default='U', max_length=1),
        ),
    ]
