# Generated by Django 2.2.1 on 2019-10-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='email_addr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='job_type',
            field=models.CharField(choices=[('a', 'Skilled'), ('b', 'Unskilled')], default='b', max_length=1),
        ),
    ]
