# Generated by Django 2.2.1 on 2019-10-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20191018_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='email_addr',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='proj',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='employment',
            name='job_type',
            field=models.CharField(choices=[('S', 'Skilled'), ('U', 'Unskilled')], default='b', max_length=1),
        ),
    ]
