# Generated by Django 2.2.1 on 2019-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20191018_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='project',
        ),
        migrations.AlterField(
            model_name='employment',
            name='job_type',
            field=models.CharField(choices=[('S', 'Skilled'), ('U', 'Unskilled')], default=0, max_length=1),
        ),
    ]
