# Generated by Django 2.2.1 on 2019-10-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_auto_20191018_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='email_address',
        ),
    ]
