# Generated by Django 2.2.1 on 2019-10-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_remove_employment_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='age',
        ),
    ]
