# Generated by Django 2.2.1 on 2019-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_remove_employment_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='job_type',
            field=models.CharField(choices=[('S', 'Skilled'), ('U', 'Unskilled')], default='U', max_length=1),
        ),
    ]
