# Generated by Django 2.2.1 on 2019-10-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191018_0747'),
        ('employment', '0007_auto_20191018_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employment',
            name='email_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
