# Generated by Django 2.2.1 on 2019-10-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_auto_20191018_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='project',
            new_name='project_title',
        ),
    ]
