# Generated by Django 2.2.1 on 2019-10-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_auto_20191018_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='project_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
