# Generated by Django 2.2.1 on 2019-10-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='proj',
            new_name='project',
        ),
    ]
